/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "helqyihwqhcbgxvsaowx"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlbHF5aWh3cWhjYmd4dnNhb3d4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4MTUxMjQsImV4cCI6MjA4ODM5MTEyNH0.JZ-kP-Af7_18nCzgOG-kOhfZCGQOA9OMa8DN8WpdyrU"